permalink: pretty
markdown: rdiscount
highlighter: pygments
url: http://hyperstudio.github.io/playbook
baseurl: http://hyperstudio.github.io/

collections:
  - plays

sass:
    sass_dir: assets/_sass
